# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('tipo_certificado', models.CharField(max_length=100)),
                ('examenes_practicados', models.CharField(max_length=1000)),
                ('telefono', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('estado_civil', models.CharField(max_length=50)),
                ('escolaridad', models.CharField(max_length=50)),
                ('profesion', models.CharField(max_length=100)),
            ],
        ),
    ]
